name: "TeddyCloud"
description: "local alternative api for toniebox"
version: "0.6.4-3"
slug: "teddycloud"
stage: experimental
webui: "https://[HOST]:[PORT:8443]"
watchdog: "https://[HOST]:[PORT:8443]"
arch:
  - amd64
  - armv7
  - aarch64
ports:
  80/tcp: null
  443/tcp: 443
  8443/tcp: 8443
map:
  - addon_config:rw
